version = 1

exclude_patterns = [
  "plugins/**",
  "assets/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[analyzers]]
name = "test-coverage"
enabled = true