deployments:
  gothamist-vue-3:
    port_forwarding:
      80:3000
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    run_options:
      --env NUXT_HOST=$NUXT_HOST
      --env NUXT_PORT=$NUXT_PORT
    pre_launch:
      context: squash_host
      command: /home/test-instance/squash_pre_build.sh